[tools]
node = '22'

[env]
_.path = ["./node_modules/.bin"]

[tasks.install]
description = 'Installs dependencies with pnpm'
run = 'corepack enable && pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.start-vscode]
description = 'Starts VSCode with the extension loaded'
run = 'code --inspect-extensions=5858 --extensionDevelopmentPath=$(pwd)'
sources = ['src/**', 'mise.toml', 'package.json', 'syntaxes/**']

[tasks.watch-vscode]
run = 'mise watch -t start-vscode'

[tasks.start-vscode-inspect-brk]
description = 'Starts VSCode with the extension loaded. Pauses on the first line of the extension'
run = 'code --inspect-brk-extensions=5858 --extensionDevelopmentPath=$(pwd)'

[tasks.dev-extension]
depends = ['install']
description = 'Builds the project in watch mode'
run = 'rsbuild dev'

[tasks.dev-webviews]
description = 'Webviews'
run = 'node --run dev-webviews'
depends = ['install']

[tasks.dev]
description = 'Starts the project in watch mode and opens the extension in VSCode'
depends = ['dev-extension', 'dev-webviews', 'start-vscode']

[tasks.dev-reload-vscode]
description = 'Starts the project in watch mode and opens the extension in VSCode. Reload VSCode on changes'
depends = ['dev-extension', 'dev-webviews', 'watch-vscode']

[tasks.ts-check]
description = 'Type-check the project'
run = 'node --run ts-check'
sources = ['src/**/*.ts']

[tasks.biome-lint]
description = 'Lint the project with biome'
run = 'node --run lint'
sources = ['src/**/*.ts']

[tasks.lint]
description = 'Lint the project + type-check'
depends = ['ts-check', 'biome-lint']

[tasks.lint-fix]
description = 'Lint the project + type-check and fix issues'
run = 'node --run lint-fix'

[tasks.test]
description = 'Run tests (with bun)'
run = 'node --run test'

[tasks.check]
description = "Lint, type-check, and test the project"
depends = ['lint-fix', 'test', 'ts-check']
