[tools]
node = '22'

[tasks.install]
run = 'pnpm install'

[tasks.dev]
depends = ['install']
run = 'node --run dev'

[tasks.ts-check]
run = 'node --run ts-check'
sources = ['src/**/*.ts']

[tasks.biome-lint]
run = 'node --run lint'
sources = ['src/**/*.ts']

[tasks.lint]
depends = ['ts-check', 'biome-lint']

[tasks.lint-fix]
run = 'node --run lint-fix'